### PR TITLE
Small changes to run prepro.py

### PR DESCRIPTION
**Pull request by dmesquita**
At first the goal was to add feedback while the script was running, but performance got worse so I gave up. But I fixed some little things for being able to run the file:
1. Add __init__.py to /drqa so we can import str2bool
2. Add encoding type to `load_wv_vocab` and `build_embedding` functions (I don't know if it's my machine configuration but I was getting some UnicodeDecodeErrors)

### CODE REVIEW

**Comment by hitvoice** [comment]
Thanks for your contribution! ^ ^
2 questions:
1. What does the "performace" mean, running time or preprocessing result? Is the "feedback" here referring to the tqdm progress bar? 
2. What's your OS & system language? The simple "open" function works for me on Mac and Ubuntu with system language set to English.

**Comment by dmesquita** [comment]
Sure :)

1. Yep, the feedback is referring to tqdm progress bar and also "loading" messages with `itertools.cycle(['-', '/', '|', '\\'])`. The "performance" is about the running time, while I was testing if I used the messages it took much longer to finish the script. The reason to add this feedback was that at the first attempts I was not sure if everything was running ok or if I got an error or my screen was frozen or something (I'm using a server through ssh).
2. Good question, now that I checked the language of my server is not set.
```
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
[...]
LC_ALL=
```
I don't have access to the administration directory (my user is not root), so I did this workaround.
OS: Ubuntu 16.04.3 LTS (GNU/Linux 3.10.0-514.16.1.el7.x86_64 x86_64)

**Comment by hitvoice** [comment]
@dmesquita Hi, I made some modifications to the code (14cd4c214f6aa7e1e6dccafc64d2268aecf52760). Now "prepro.py" runs 3x faster but I haven't figured out how to use tqdm in parallel codes. I'll be glad if you have some ideas on this and make some contributions!

**Comment by hitvoice** [comment]
Hello,
I add the tqdm progress bar to "prepro.py" (9d407ea603ed1996aa75692998b4c1ad8dafb0d2) and this progress bar have ignorable effects on running time. Hope it helps! :)

**Comment by dmesquita** [comment]
Thank you so much!
This semester I attended a Deep Learning course at my Uni and it was the first time I had to dive deep into the subjects, your project was really helpful on this journey! :D

**Pull request closed without merging**
