### PR TITLE
replace async with non_blocking for pytorch 1.0

### PR DESCRIPTION
**Pull request by brettkoonce**
this argument got renamed for pytorch 1.0:   https://pytorch.org/docs/stable/notes/cuda.html
can put it into a branch as well if you would like to keep things separate.

### CODE REVIEW

**Comment by brettkoonce** [comment]
weird, only seeing this with python3.7?  please check before you merge.

**Comment by brettkoonce** [comment]
worked without this on a box with python 3.5 (above was an issue on python 3.7), might be related to the python version?

**Comment by hitvoice** [comment]
This argument seems unnecessary and can be removed for better compatibility. According to the doc, 
> By default, GPU operations are asynchronous.

This argument only forces non-blocking even with the environment variable CUDA_LAUNCH_BLOCKING=1 (if I understand the doc correctly). So is removing this argument a better solution?

**Comment by brettkoonce** [comment]
You know better than I if it's needed, it certainly can be dropped as well.

I only use the launch blocking flag to force error logging, for what it's worth.

**Comment by hitvoice** [comment]
OK. Could you please remove this flag ("async=True")?  After that, I can merge the updated branch.

**Pull request merged**
